apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-aggregator-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: job.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-aggregator-service
                port:
                  number: 8000