apiVersion: v1
kind: Service
metadata:
  name: job-aggregator-service
  namespace: production
spec:
  selector:
    app: job-aggregator
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort