apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: job-aggregator
  namespace: argocd

spec:
  description: Job Aggregator application project

  sourceRepos:
    - https://github.com/oumhanane/job-aggregator.git

  destinations:
    - namespace: default
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
